schema_version: 1

context:
  name: gempakio
  version: "1.4.4"
  python_min: "3.11"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a903971834029511ceee0e4f8fdf95eb70f97e0440236e36721b057d0e629e91
build:
  noarch: python
  number: 2
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - pandas
    - pyproj
    - xarray

tests:
  - python:
      imports:
        - gempakio
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://github.com/nawendt/gempakio
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Read and write GEMPAK file formats.
  description: |
    gempakIO is a pure-Python package that will read and write GEMPAK grid, sounding, and surface data as well as other GEMPAK file formats.
  repository: https://github.com/nawendt/gempakio
  documentation: https://github.com/nawendt/gempakio

extra:
  recipe-maintainers:
    - nawendt
